# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

destination: _site
sass:
  sass_dir: _sass
  style: expanded # compressed # expanded

# permalink and highlighter
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

# SEO settings
title: Shubham Lahoti
description: 'My blog'
keywords: 'Jekyll, Blog, Shubham, Lahoti'

# Site settings
url: https://www.linkedin.com/in/shubham-lahoti/
#baseurl: "/dotX"
baseurl: ''

# Author settings
author:
  name: Shubham Lahoti
  job: Developer/Coder/Student
  thumb: /images/author.jpg
  email: lahotishubham03@gmail.com
  url: https://www.linkedin.com/in/shubham-lahoti/
  github: http://github.com/shubhamlahoti01
  facebook: https://www.linkedin.com/in/shubham-lahoti/

# google_analytics: UA-52446115-1
repo: http://github.com/shubhamlahoti01/shubhamlahoti01.github.io
# comments
#disqus_shortname: "fernandomoreira"
